name: apiverve_heicconverter
description: HEIC Converter transforms Apple HEIC and HEIF images to web-friendly formats. Perfect for processing iPhone photos that need to be converted for websites, apps, or services that don't support HEIC.
version: 1.1.14
homepage: https://apiverve.com/marketplace/heicconverter?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/heicconverter-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
